version: '3.6'

services:
  backend:
    image: orkeystore/server:latest
    ports:
      - '3000:3000'
    environment:
      ADMIN_PASSWORD: 'password'
      PRIVATE_HOST: 'http://localhost:3000'
      SWAGGER: 1
